### ISSUE TITLE
Trouble getting syntax highlighting to work for R code

### ISSUE THREAD

**Issue by kbenoit** [digitalcraftsman/hugo-material-docs#11]
Excellent theme!

I'm struggling to get syntax highlighting for R code working, for a code block like this:
```
    ```r
    ## devtools required to install quanteda from Github
    devtools::install_github("kbenoit/quantedaData")
    ```
```
and I am not having any luck. I'm publishing this to my `gh-pages` using the `deploy.sh` bash script. (See my tests so far at http://kbenoit.github.io/testing/readme/#how-to-install). 

Any help greatly appreciated!

**Comment by digitalcraftsman** [comment]
Hi @kbenoit,

excuse my late response. The syntax highlighting in the [original theme](https://squidfunk.github.io/mkdocs-material/customization/) is visually quite limited and a Python-based Markdown extension was used to do this.

Your Markdown code looks fine. However, it was difficult to find a theme that has good contrast on a light grey background. Maybe I can find a similar theme to Github's. 

PS: Your [demo](https://kbenoit.github.io/testing/readme/#how-to-install) looks broken. [Here](https://discuss.gohugo.io/t/themes-not-showing-on-github-page/3073/4?u=digitalcraftsman) you can find a fix.

**Comment by kbenoit** [comment]
Thanks for the fix!
