### ISSUE TITLE
support for .pre menu context in config.toml

### ISSUE THREAD

**Issue by choosefreesoftware** [digitalcraftsman/hugo-material-docs#12]
I am trying to insert an awesome font icon before the menu sections in the nav bar. However, there isn't a {{.pre}} section in the nav layouts. This means I can't insert HTML before the title of the section, which is problematic for my project. Is there a simple way for me to insert this into my project?
Thanks.

**Comment by digitalcraftsman** [comment]
Hello @choosefreesoftware,

have a look at 8d3309bee0f0a5a9db1459565ca76c47c54de4d7. In your config file you can add the attribute `pre` followed by the HTML element that you want to prepend.

I tried to add a fontawesome icon and it works fine. But the font-size is a but small for an icon. Maybe you adjust it yourself.

**Comment by choosefreesoftware** [comment]
Thanks! All I had to do was insert `{{ $currentMenuEntry.Pre }}` into the nav_link.html layout.
