### ISSUE TITLE
!!! warning "Don't try this at home"

### ISSUE THREAD

**Issue by Hitaro** [digitalcraftsman/hugo-material-docs#14]
{{< warning title="Don't try this at home" >}}
    Nothing to see here, move along.
    {{< /warning >}}

Isn't there a way to add warnings/notes in the way of mkdocs ([+](http://squidfunk.github.io/mkdocs-material/getting-started/))? The current way is a bit hard for none-technical users to deal with.

**Comment by digitalcraftsman** [comment]
Hi @Hitaro,

Hugo uses [Blackfriday](https://github.com/russross/blackfriday) to convert your Markdown files into HTML. The `!!!` aren't part of Markdown itself but Blackfriday has a couple of extensions that allow you to add such features. Some of them are usable in Hugo.

However, I had the same thought and created a feature request (see russross/blackfriday#246). Even the original Material theme uses a [Markdown extension](https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml#L48) for these admonition blocks.

A theme-based integration would be out of my scope. Shortcodes like your example above are the easiest way.

Cheers,
Digitalcraftsman
