### ISSUE TITLE
Changing the background for inline fenced text to non-transparent and better KBD tags

### ISSUE THREAD

**Issue by chhh** [digitalcraftsman/hugo-material-docs#15]
The default styling for inline fenced blocks has no background color, unlike the inline fenced blocks on GitHub (e.g. `this is fenced inline text`). Most markdown processors add some background as well.

The same is true for  ''kbd tags (e.g. here is the 'Shift' word wrapped in 'kbd' tags: <kbd>Shift</kbd>). But the theme renders it as just monospaced text.

Is it possible to add those back? All I need is some guidance as to what _css_ to add to the site to make it support those things.

Thanks, it's and awesome theme that you've made there!

**Comment by digitalcraftsman** [comment]
Hello @chhh,

first of all I'm ported the [original theme](https://github.com/squidfunk/mkdocs-material) to Hugo - I didn't created it. In general I consider the original theme as upstream repository and pull all changes (including the stylesheets) from there.

Therefore, I don't know the details of the stylesheet's structure. But I think it's a good idea to propose the support for fenced code blocks and `kbd` tags.

After collecting feedback the original theme get's a [slight overhaul](https://github.com/squidfunk/mkdocs-material/issues/2#issuecomment-207603352). 

Adding youe requested features shouldn't be very difficult. I don't want to let both themes drift apart while my port becomes it's *own* project.

**Comment by digitalcraftsman** [comment]
I created the corresponding issues:

- squidfunk/mkdocs-material#25
- squidfunk/mkdocs-material#26

**Comment by chhh** [comment]
Thanks! Let's wait and see then

**Comment by squidfunk** [comment]
Both fixed in master and 0.2.3.

**Comment by digitalcraftsman** [comment]
@squidfunk thank you for the update. 

@chhh I updated the stylesheets in 673512466d8d73137544b2f5627d1218731a01b5
