### ISSUE TITLE
Customizing the colors for admonitions

### ISSUE THREAD

**Issue by chhh** [digitalcraftsman/hugo-material-docs#16]
The default colors for admonitions are very saturated, so far I've found that I can supply my own custom css in the `.toml` file, that will be loaded after the deafult one. But this is not obvious and took some grepping to find the right classes in the compressed `application.css` to override.

I think it is worth it to make those 2 colors ('note' and 'warning') customizable via `config.toml`.

In general it would be super-awesome if you could replace the current color limitations. I don't know Go and Hugo well enough to say if it's easy or not to generate custom `.css` with templates as well. You definitely have some script to generatre the all the color-scheme css, I guess it should be possible to just have one set of classes there and substitute user-provided 2 color parameters in it to generate all the various needed css classes.

**Comment by digitalcraftsman** [comment]
Hello again,

as I said, I pull the (generated & minified) stylesheets from the original project. The stylesheets are written in SASS and then be compiled to CSS. You can find the SASS files [here](https://github.com/squidfunk/mkdocs-material/tree/master/src/assets/stylesheets). It should be easy to change the variables in the SASS files and to regenerate them.

> I don't know Go and Hugo well enough to say if it's easy or not to generate custom .css with templates as well.

Using custom preprocessors is one of most requested features of Hugo. Furthermore, I started an attempt to make variables of the config file [accessible in stylesheets](https://github.com/spf13/hugo/pull/1431). There are plans to rethink the internal design of Hugo to make this possible but it will take some time.
