### ISSUE TITLE
An issue w/ creating nested menu

### ISSUE THREAD

**Issue by emzi** [digitalcraftsman/hugo-material-docs#17]
Hi @digitalcraftsman

It's described [here](https://digitalcraftsman.github.io/hugo-material-docs/getting-started) how to create a nested menu. But it seems there's an issue around it:

- Name of the content file is added to the sidebar, while the 'title' is expected.

![An-image-has-NOT-been-loaded-here](https://cloud.githubusercontent.com/assets/1899175/14742060/8733a320-08af-11e6-98ec-1236e3073501.png)

####  ❱ `cat config.toml`

    ...
    [[menu.main]]
    	name   = "Home"
    	url    = "/"
    	weight = 0
    
    [[menu.main]]
    	name   = "Testing"
    	url    = "testing/"
    	weight = 10
    
    [[menu.main]]
    	name   = "Hello World!"
    	url    = "aa-bb-cc/"
    	weight = 20
    ...

#### content ❱ `tree -L 2`

    .
    ├── aa-bb-cc
    │   ├── index.md
    │   ├── sub-menu-1.md
    │   └── sub-menu-2.md
    ├── index.md
    └── Testing
        └── index.md

#### content/aa-bb-cc ❱ `head sub-menu-1.md`

    ---
    date: 2016-04-22T16:00:47+03:30
    title: SubMenu 1
    menu:
      main:
        parent: Hello World!
        identifier: SubMenu 1
        weight: 0
    ---

---
- By using a native language (in my case: Persian), it's even disapeared!

![salaam-donya_screenshot](https://cloud.githubusercontent.com/assets/1899175/14742827/69cf2bf2-08b3-11e6-80cf-b952328c9ad5.png)

![screenshot](https://cloud.githubusercontent.com/assets/1899175/14742947/068cd606-08b4-11e6-81c3-dff58c19aaf9.png)

**Comment by gravis** [comment]
I have the same issue here (with hugo 0.15)

**Comment by gravis** [comment]
It would be nice also to have this layout:

<img width="260" alt="screenshot 2016-05-07 16 00 02" src="https://cloud.githubusercontent.com/assets/12752/15094289/d607cb52-146c-11e6-9407-8073425171f9.png">

but "Installation", "Setup", etc. are actually pages of this section.
Thanks

**Comment by digitalcraftsman** [comment]
Hello @emzi,

excuse the delay. I'm trying to fix the title of the section in the sidebar. The initial obstacle is that this link doesn't actually point to a page or content file. It's just a link. Therefore, I had to use some (hacky) workarounds to get it done.

@gravis 

> It would be nice also to have this layout:
<img width="260" alt="screenshot 2016-05-07 16 00 02" src="https://cloud.githubusercontent.com/assets/12752/15094289/d607cb52-146c-11e6-9407-8073425171f9.png">

The orange line on the left is only intended for the table of contents. You can nest all pages of a section as @emzi described it in his comment above. For example, `Aa-Bc-Cc` becomes grey and bold in the menu. Below you see a nested list will all pages of this section.

![](https://cloud.githubusercontent.com/assets/1899175/14742060/8733a320-08af-11e6-98ec-1236e3073501.png)

**Comment by gravis** [comment]
This is what I have:

![screenshot 2016-05-18 10 44 21](https://cloud.githubusercontent.com/assets/12752/15363093/85dbaadc-1ce5-11e6-86c0-8681a21b54d9.png)

the scrollspy is still working:

![screenshot 2016-05-18 10 44 53](https://cloud.githubusercontent.com/assets/12752/15363103/90ca2d6a-1ce5-11e6-9853-8652b0ccde75.png)

**Comment by gravis** [comment]
(with #19 of course)

**Comment by digitalcraftsman** [comment]
#19 fixed the issue that I have had with the master branch.
