### ISSUE TITLE
Homepage and list templates

### ISSUE THREAD

**Issue by kcgthb** [digitalcraftsman/hugo-material-docs#20]
Hi!

Thanks for porting [Martin](https://github.com/squidfunk)'s great theme to Hugo.

Since Hugo supports different layouts and templates (list, single, homepage), do you think there would be a way to implement them in the Material-docs theme? They're not available in the original theme, as MkDocs only supports single page layouts, but being able to have them all would be an awesome addition.

Thanks!

**Comment by digitalcraftsman** [comment]
Hello @kcgthb,

I added a template for a section list. Let me know what you think.
