### ISSUE TITLE
Problems with huge-material-docs submodule

### ISSUE THREAD

**Issue by kbenoit** [digitalcraftsman/hugo-material-docs#25]
Hi - Thanks so much for setting this beautiful system up, and for providing such generous help for it.

I'm having a problem where it looks like my gh-pages should be OK, but it's not. I'm getting this message in the **Settings** page of https://github.com/kbenoit/TAUR:

> Your site is having problems building: The submodule registered for ./themes/hugo-material-docs could not be cloned. Make sure it's using https:// and that it's a public repo. For more information, see https://help.github.com/articles/page-build-failed-invalid-submodule.

And http://kbenoit.github.io/TAUR generates a 404 error. 

Thanks for any help!

**Comment by digitalcraftsman** [comment]
Hello @kbenoit,

you don't explicitly mention your deploymtent method for this theme but I might found the issue. You quote states:

> Make sure it's using https:// and that it's a public repo.

Your [`.gitmodules`](https://github.com/kbenoit/TAUR/blob/master/.gitmodules#L3) file on the other hand uses SSH. Try to use the HTTPS link instead.

**Comment by kbenoit** [comment]
Thanks, I have changed the `.gitmodules` files on both master and gh-pages. But I am still getting (in Settings)

>  Your site is having problems building: Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-build-failures.

I think it's related to the way that https://github.com/kbenoit/TAUR/tree/master/themes is linked - but I don't know much about how git uses these sorts of submodule links.

**Comment by digitalcraftsman** [comment]
If you have cloned your repository, is the `themes/hugo-material-theme` folder empty?

The theme is a repository inside a repository. If you just run `git clone` the `hugo-material-theme` folder remains empty, because you didn't cloned the repositories recursively (i.e. you didn't cloned the theme repository).

Try `git clone --recursive https://github.com/kbenoit/TAUR/`

**Comment by digitalcraftsman** [comment]
Closing this as stall. Reopen this issue if it is still relevant.
