### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by haraldnicola** [digitalcraftsman/hugo-material-docs#26]
Hi @digitalcraftsman I did not find your email.
I would like to know if you are available to create a Hugo Theme for my website.

You can contact me at akkiashtc@gmail.com 

Best

**Comment by digitalcraftsman** [comment]
Hello @haraldnicola,

thank you for the offer and you're not the first one asking but I don't do contract work like this. Most of my themes are ports of existing themes. So the actual creation of a design and the implementation in CSS part is not my one of my strengths.

I would suggest to ask the Hugo community in the [forum](https://discuss.gohugo.io/).

Cheers,
Digitalcraftsman
