### ISSUE TITLE
params.palette is invalid

### ISSUE THREAD

**Issue by mr-kelly** [digitalcraftsman/hugo-material-docs#29]
[params]
custom_css = ['custom.css']

Custom css is invalid, it will make nothing show....

[params.palette]
  primary = "deep purple"
  accent  = "light green"

Color palette is invalid with these params....

**Comment by digitalcraftsman** [comment]
Hello @mr-kelly,

your issue should be fixed with #27. Let me know if it works.

**Comment by digitalcraftsman** [comment]
Closing this as stall.
