### ISSUE TITLE
multilingual

### ISSUE THREAD

**Issue by joeblew99** [digitalcraftsman/hugo-material-docs#34]
Hey

i saw that this is now close to being complete: https://github.com/digitalcraftsman/hugo-multilingual

I was wondering if you plan to get this repo working as Multi-linugual too ?
I reckon i could help.
From what i saw of the first repo above its not a huge amount of change.
Just no docs yet really, so i figured i can just follow your lead on the one above.

let me know your thoughts

**Comment by joeblew99** [comment]
mhh. maybe something on your end ?

```

x-MacBook-Pro:hugo apple$ git clone git@github.com:digitalcraftsman/hugo-material-docs.git themes/hugo-material-docs
Cloning into 'themes/hugo-material-docs'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
x-MacBook-Pro:hugo apple$ 


````

**Comment by digitalcraftsman** [comment]
Hello @joeblew99,

the hugo-multiligual is only a temporary repository that I use as playground and to demonstrate some bugs that I mentioned in issues. You can find the actual (wip) theme [here](https://github.com/digitalcraftsman/hugo-scriptor-theme). As far as I know it's the first theme with i18n support and I created it as some kind of orientation/guideline for others.

You can already find some documentation about the multilingual feature in the Hugo repo. The upstream project (this is a port) currently makes a huge redesign process. I have to think about it if I add the multilingual feature seperately or with the redesign to ensure compatibility.

PS: I'll change switch to https for cloning

**Comment by digitalcraftsman** [comment]
#3 already covers the integration as a reminder. I'll close this issue on refer to #3 instead for questions, discussions etc.
