### ISSUE TITLE
Last character of title clipped / truncated from heading

### ISSUE THREAD

**Issue by jacobq** [digitalcraftsman/hugo-material-docs#37]
Regardless of the length of the title defined in `config.toml` it seems that this theme drops the last character. For example, using `title = "Material Docs"` the top of the page shows "Material Doc" even though the full/correct title appears elsewhere.
![hugo-material-docs-bug](https://cloud.githubusercontent.com/assets/1633459/18689711/29970f32-7f50-11e6-97ef-af8e2ff3b9fc.png)

For now I am working around this by appending a space to the end, but this is annoying and seems like it should be an easy bug to squash.

**Comment by jacobq** [comment]
Upon looking into this further it seems this is partially intentional as there is a `singularize` helper stripping the `s` from the end. Unfortunately, the title of my project ends with an `s` but is singular so all this does is mess up the name. I know I can fork and modify, but is there a cleaner way to avoid this problem?

**Comment by digitalcraftsman** [comment]
Hello @jacobq 

I can actually remove the `singularize` function. No need to fork :wink:
