### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by hfogelberg** [digitalcraftsman/hugo-material-docs#38]
Completely new to Hugo.

Is it possible to set the email address in config.toml? I tried setting it in the social section together with Github and Twitter as ``email="john.doe@gmail.com"``, but it didn't appear. Any other way of doing it? 

Thanks

**Comment by digitalcraftsman** [comment]
Hello @hfogelberg,

I added in a3bb5f89588845720a3077bc33eaa2bb32b99e67a link to the sidebar that opens your standard email client if you click on it. Does this fix your issue?

**Comment by hfogelberg** [comment]
Perfect! Thanks for the quick help.
