### ISSUE TITLE
Javascript sources

### ISSUE THREAD

**Issue by sergeykaul** [digitalcraftsman/hugo-material-docs#39]
Hi, I like this theme. I want to modify the application.js slightly. Is it possible to share the js sources?

**Comment by digitalcraftsman** [comment]
Hello @sergeykaul,

have a look at the [upstream project](https://github.com/squidfunk/mkdocs-material). It contains the original JS files.

**Comment by sergeykaul** [comment]
Thank you

**Comment by markvincze** [comment]
Hi @digitalcraftsman,

Do you happen to have the non-minified version of the current `application.js`? (I checked the one in the upstream, but that has changed a lot since then)

Thanks!
