### ISSUE TITLE
 Support for collapsible sections in navigation

### ISSUE THREAD

**Issue by amadfida** [digitalcraftsman/hugo-material-docs#44]
Is it possible to have section menus and content menus like 

https://developers.google.com/protocol-buffers/docs/gotutorial 

Looks like this was already done for mkdoscs

https://github.com/squidfunk/mkdocs-material/issues/46

**Comment by digitalcraftsman** [comment]
Hello @amadfida,

as you already noticed the upstream project get's an overhaul that includes collapsible content menus. Once version 1.0.0 of the upstream project is released I will port the changes to this theme as well, including the collapsible menus. 

This feature will be included automatically. Therefore, I'll close this issue. But I'll keep it in mind ;)

**Comment by amadfida** [comment]
Hi there - I know you have taken a mental note of this :) but saw this update https://github.com/squidfunk/mkdocs-material/issues/46 from Martin - based on the list it seems all the Look and feel type of work is done and he is very close to releasing it. I was wondering if this is a good time to start the upgrade?

**Comment by digitalcraftsman** [comment]
Martin posted this in the issue 6 days ago:

> I will try to accomplish everything within the next week to release 1.0.0-rc.1, because I will be on vacation from 18 Nov to 12 Dec. The RC can then be tested and we should be able to push 1.0.0 out at the end of the year. 

I'll wait at least until Martin will publishes an release candidate. With those I can expect that most things are already stable and don't change on a large scale. The current progress in his theme looks good so let's wait. 

This upgrade will also connected with backwards-compatibility issues since I'm because adding i18n support will change a lot in the configuration. Hence I'll have to starting to version this theme.

**Comment by amadfida** [comment]
Sounds good - looks like Martin is very or should be - looking forward to the upgrade.

**Comment by amadfida** [comment]
Hey- just checking in to see if you feel https://github.com/squidfunk/mkdocs-material/issues/46#issue-176263632 is at a good point to start migration ?

**Comment by digitalcraftsman** [comment]
> just checking in to see if you feel squidfunk/mkdocs-material#46 (comment) is at a good point to start migration ?

Martin did a fantastic work and it looks already very polished. But he's still pushing a lot of smaller changes. It's easier to keep track once he's done when I start to change the whole layout of this port.

Furthermore, Hugo v0.18 introduced some changes that might has influence on the way how the content organized and rendered (see #52). Hugo v0.18.1 is likely to be released in the near future that should fix this issue.

I'll wait once all this aspects a sort of stabilized. Stay tuned!
