### ISSUE TITLE
Commercial support 

### ISSUE THREAD

**Issue by amadfida** [digitalcraftsman/hugo-material-docs#54]
@digitalcraftsman I am interested in discussing a possibility of getting your help on our docs project that uses hugo and your theme - would it possible for you to email me a contact information if you are interested? 

You can reach me @ amad.fida@brinqa.com

Thanks

Amad

**Comment by digitalcraftsman** [comment]
Hello @amadfida,

thanks for your request but I see all my Hugo themes rather a side projects without any commercial interest in mind.

However, please feel free to open an issue questions regarding the theme or feature requests.

Regards,
Digitalcraftsman

**Comment by amadfida** [comment]
Closing it as now we have switched to using Mkdocs as we are really building a docs site and its working well for us.
