### ISSUE TITLE
feed

### ISSUE THREAD

**Issue by onrea** [digitalcraftsman/hugo-material-docs#6]
Does it support for [rss](http://gohugo.io/templates/rss/)? I couldn't find any rss.xml file.

**Comment by digitalcraftsman** [comment]
I linked the RSS feed in the head of each page.

**Comment by onrea** [comment]
Great, index.rss works like a charm.

This is not important, though, but, [Inoreader plugin](https://addons.mozilla.org/en-US/firefox/addon/inoreader-companion/?src=api) still can not recognize the feed automatically! _Inoreader.com_ service went popular after turning off google feed reader. Indeed, the plugin cannot recognize the feed of none of _themes.gohugo.io_!

**Comment by digitalcraftsman** [comment]
I don't know Inoreader but I've tested the auto-detection with Feedly and it worked like a charm.
