### ISSUE TITLE
Minimum version should be 0.19 instead of 0.20

### ISSUE THREAD

**Issue by ArtFlag** [digitalcraftsman/hugo-material-docs#64]
Hello,

I am looking in this nice theme and I just noticed that commit 1b14974cb38b595e6f2e1e917bcace8deeeb73e8 prevents us from using the theme as 0.20 is not out yet.  `.Now` was deprecated in 0.19, so I believe min-version should be 0.19?

Thanks!

**Comment by digitalcraftsman** [comment]
Hello @ArtFlag,

tl;dr: Hugo v0.20 will be released tomorrow.

Maybe I was a bit quick with this change but how does this affect the usage of the theme? Hugo v0.19 builds a website with this theme fine and prints a non-blocking error warning.

**Comment by ArtFlag** [comment]
Ok excellent news :)

It seems my website didn't display at first for another reason, but I did see the error message linked to the website conf during the build so I assumed it was related to this.  

So I guess everything's fine then! 

Thank you!
