### ISSUE TITLE
Index's pagination always points to a broken link "Tags"

### ISSUE THREAD

**Issue by blacktop** [digitalcraftsman/hugo-material-docs#68]
![screen shot 2017-07-02 at 10 54 13 am](https://user-images.githubusercontent.com/6118188/27771877-e4fb638c-5f14-11e7-8158-1a816e022be1.png)

This leads to a 404 and I am not sure how to fix it?

This is a truly beautiful theme.  Thank you

**Comment by wonslung** [comment]
I'm having this same issue....thanks for any help

**Comment by wonslung** [comment]
actually i figured this out:

in each section index.md you need to add weight option

weight: 20

for example

**Comment by chhh** [comment]
same issue here

**Comment by jesposito** [comment]
Same issue - is there a quick fix?

**Comment by blacktop** [comment]
I was able to fix it by changing this line: https://github.com/digitalcraftsman/hugo-material-docs/blob/master/layouts/partials/footer.html#L53

to this: 

```html
  {{ $title := (index (.Site.Pages.ByWeight) 1).Title  }}
  {{ $permalink := (index (.Site.Pages.ByWeight) 1).Permalink }}
```

However, now there is a `Last` link but NO `Next` link. :(

**Comment by blacktop** [comment]
FYI this also fixes the issue https://github.com/digitalcraftsman/hugo-material-docs/pull/73

**Comment by RTodorov** [comment]
Why is this issue closed? It's still happening and not fixed in master. Can I open a PR and get it merged?
