### ISSUE TITLE
Which css element is controlling the position of white background of article part?

### ISSUE THREAD

**Issue by Hitaro** [digitalcraftsman/hugo-material-docs#9]
Hi, Because of a Japanese work, I needed to move the 'drawer' sidebar  to right side: `.drawer { float: right; }`. I did it successfully. And I also set other elements to be compatible.

But, I couldn't push the white background (of `article`) to left side; Which element is controlling it?!

Kind regards

**Comment by digitalcraftsman** [comment]
Hello @Hitaro,

it's good idea to implement an option to reverse the layout. However, this theme was orginally created for Hugo's companion [MkDocs](http://www.mkdocs.org/) and I only ported it. Therefore, I'm not familiar with the internal structure of the stylesheet.

It's probably better to repost this issue in the repository of the [original theme](https://github.com/squidfunk/mkdocs-material/issues). I consider the original theme as upstream project, i.e. I'm merge all changes / additions that are made in the original codebase into my port.

I'm glad to merge such addtions once they appear in the original.

**Comment by Hitaro** [comment]
Thanks for the info.

**Comment by digitalcraftsman** [comment]
> I think it cannot be done simply for each theme without manipulated custom CSS/JS codes.

Some themes are more complex than others.
