### ISSUE TITLE
failed on hugo 0.48 win64

### ISSUE THREAD

**Issue by wuyongyi** [digitalcraftsman/hugo-material-docs#96]
when run with

`hugo server
`
, there is error message like:

`Ref "getting-started/index.md": page not found`

can't find out what is happening.
(other theme from you like "Alabaster" works fine in this version of hugo.  )

**Comment by hellt** [comment]
same with me on darwin

**Comment by hellt** [comment]
as per https://github.com/digitalcraftsman/hugo-material-docs/issues/84 renaming of `./content/index.md` to `./content/_index.md` solved the issue

**Comment by wuyongyi** [comment]
@hellt 👍 
Thanks for the message, I try it in darwin and it works now.
